#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Botiya
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Botiya")]
	public partial class BotiyaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPerson(Person instance);
    partial void UpdatePerson(Person instance);
    partial void DeletePerson(Person instance);
    partial void InsertProduct(Product instance);
    partial void UpdateProduct(Product instance);
    partial void DeleteProduct(Product instance);
    partial void InsertVahed(Vahed instance);
    partial void UpdateVahed(Vahed instance);
    partial void DeleteVahed(Vahed instance);
    #endregion
		
		public BotiyaDataContext() : 
				base(global::Botiya.Properties.Settings.Default.BotiyaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BotiyaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BotiyaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BotiyaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BotiyaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Person> Persons
		{
			get
			{
				return this.GetTable<Person>();
			}
		}
		
		public System.Data.Linq.Table<Product> Products
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
		
		public System.Data.Linq.Table<Vahed> Vaheds
		{
			get
			{
				return this.GetTable<Vahed>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertPersons")]
		public int InsertPersons([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FName", DbType="NVarChar(100)")] string fName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LName", DbType="NVarChar(100)")] string lName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FatherName", DbType="NVarChar(100)")] string fatherName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodeMelli", DbType="NVarChar(10)")] string codeMelli, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Phone", DbType="NVarChar(11)")] string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mobile", DbType="NVarChar(11)")] string mobile, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address", DbType="NVarChar(MAX)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Hoqoqi", DbType="Int")] System.Nullable<int> hoqoqi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SherkatName", DbType="NVarChar(150)")] string sherkatName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fName, lName, fatherName, codeMelli, phone, mobile, address, hoqoqi, sherkatName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdatePerson")]
		public int UpdatePerson([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FName", DbType="NVarChar(100)")] string fName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LName", DbType="NVarChar(100)")] string lName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FatherName", DbType="NVarChar(100)")] string fatherName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodeMelli", DbType="NVarChar(10)")] string codeMelli, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Phone", DbType="NVarChar(11)")] string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mobile", DbType="NVarChar(11)")] string mobile, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address", DbType="NVarChar(MAX)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Hoqoqi", DbType="Int")] System.Nullable<int> hoqoqi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SherkatName", DbType="NVarChar(150)")] string sherkatName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, fName, lName, fatherName, codeMelli, phone, mobile, address, hoqoqi, sherkatName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FillPersons")]
		public ISingleResult<FillPersonsResult> FillPersons()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<FillPersonsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FillPersonsById")]
		public ISingleResult<FillPersonsByIdResult> FillPersonsById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<FillPersonsByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetPerson")]
		public int GetPerson([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fname", DbType="NVarChar(100)")] ref string fname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lname", DbType="NVarChar(100)")] ref string lname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FatherName", DbType="NVarChar(100)")] ref string fatherName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodeMelli", DbType="NVarChar(10)")] ref string codeMelli, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Phone", DbType="NVarChar(10)")] ref string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mobile", DbType="NVarChar(11)")] ref string mobile, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address", DbType="NVarChar(MAX)")] ref string address, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Hoqoqi", DbType="Int")] ref System.Nullable<int> hoqoqi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SherkatName", DbType="NVarChar(150)")] ref string sherkatName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, fname, lname, fatherName, codeMelli, phone, mobile, address, hoqoqi, sherkatName);
			fname = ((string)(result.GetParameterValue(1)));
			lname = ((string)(result.GetParameterValue(2)));
			fatherName = ((string)(result.GetParameterValue(3)));
			codeMelli = ((string)(result.GetParameterValue(4)));
			phone = ((string)(result.GetParameterValue(5)));
			mobile = ((string)(result.GetParameterValue(6)));
			address = ((string)(result.GetParameterValue(7)));
			hoqoqi = ((System.Nullable<int>)(result.GetParameterValue(8)));
			sherkatName = ((string)(result.GetParameterValue(9)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeletePerson")]
		public int DeletePerson([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteVahed")]
		public int DeleteVahed([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FillVaheds")]
		public ISingleResult<FillVahedsResult> FillVaheds()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<FillVahedsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetVahed")]
		public int GetVahed([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(200)")] ref string name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, name);
			name = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertVahed")]
		public int InsertVahed([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(200)")] string name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateVahed")]
		public int UpdateVahed([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(200)")] string name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, name);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FillPersonByLname")]
		public ISingleResult<FillPersonByLnameResult> FillPersonByLname([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lname", DbType="NVarChar(100)")] string lname)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lname);
			return ((ISingleResult<FillPersonByLnameResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Persons")]
	public partial class Person : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _FName;
		
		private string _LName;
		
		private string _FatherName;
		
		private string _CodeMelli;
		
		private string _Phone;
		
		private string _Mobile;
		
		private string _Address;
		
		private System.Nullable<bool> _Hoqoqi;
		
		private string _SherkatName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFNameChanging(string value);
    partial void OnFNameChanged();
    partial void OnLNameChanging(string value);
    partial void OnLNameChanged();
    partial void OnFatherNameChanging(string value);
    partial void OnFatherNameChanged();
    partial void OnCodeMelliChanging(string value);
    partial void OnCodeMelliChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnMobileChanging(string value);
    partial void OnMobileChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnHoqoqiChanging(System.Nullable<bool> value);
    partial void OnHoqoqiChanged();
    partial void OnSherkatNameChanging(string value);
    partial void OnSherkatNameChanged();
    #endregion
		
		public Person()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FName", DbType="NVarChar(100)")]
		public string FName
		{
			get
			{
				return this._FName;
			}
			set
			{
				if ((this._FName != value))
				{
					this.OnFNameChanging(value);
					this.SendPropertyChanging();
					this._FName = value;
					this.SendPropertyChanged("FName");
					this.OnFNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LName", DbType="NVarChar(100)")]
		public string LName
		{
			get
			{
				return this._LName;
			}
			set
			{
				if ((this._LName != value))
				{
					this.OnLNameChanging(value);
					this.SendPropertyChanging();
					this._LName = value;
					this.SendPropertyChanged("LName");
					this.OnLNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FatherName", DbType="NVarChar(100)")]
		public string FatherName
		{
			get
			{
				return this._FatherName;
			}
			set
			{
				if ((this._FatherName != value))
				{
					this.OnFatherNameChanging(value);
					this.SendPropertyChanging();
					this._FatherName = value;
					this.SendPropertyChanged("FatherName");
					this.OnFatherNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeMelli", DbType="NVarChar(10)")]
		public string CodeMelli
		{
			get
			{
				return this._CodeMelli;
			}
			set
			{
				if ((this._CodeMelli != value))
				{
					this.OnCodeMelliChanging(value);
					this.SendPropertyChanging();
					this._CodeMelli = value;
					this.SendPropertyChanged("CodeMelli");
					this.OnCodeMelliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(11)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="NVarChar(11)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this.OnMobileChanging(value);
					this.SendPropertyChanging();
					this._Mobile = value;
					this.SendPropertyChanged("Mobile");
					this.OnMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(MAX)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoqoqi", DbType="Bit")]
		public System.Nullable<bool> Hoqoqi
		{
			get
			{
				return this._Hoqoqi;
			}
			set
			{
				if ((this._Hoqoqi != value))
				{
					this.OnHoqoqiChanging(value);
					this.SendPropertyChanging();
					this._Hoqoqi = value;
					this.SendPropertyChanged("Hoqoqi");
					this.OnHoqoqiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SherkatName", DbType="NVarChar(150)")]
		public string SherkatName
		{
			get
			{
				return this._SherkatName;
			}
			set
			{
				if ((this._SherkatName != value))
				{
					this.OnSherkatNameChanging(value);
					this.SendPropertyChanging();
					this._SherkatName = value;
					this.SendPropertyChanged("SherkatName");
					this.OnSherkatNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Products")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _CodeId;
		
		private string _Name;
		
		private System.Nullable<int> _Vahed;
		
		private System.Nullable<long> _PriceKala;
		
		private System.Nullable<long> _PriceDastMozd;
		
		private System.Nullable<long> _SumPrice;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCodeIdChanging(string value);
    partial void OnCodeIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnVahedChanging(System.Nullable<int> value);
    partial void OnVahedChanged();
    partial void OnPriceKalaChanging(System.Nullable<long> value);
    partial void OnPriceKalaChanged();
    partial void OnPriceDastMozdChanging(System.Nullable<long> value);
    partial void OnPriceDastMozdChanged();
    partial void OnSumPriceChanging(System.Nullable<long> value);
    partial void OnSumPriceChanged();
    #endregion
		
		public Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeId", DbType="NChar(10)")]
		public string CodeId
		{
			get
			{
				return this._CodeId;
			}
			set
			{
				if ((this._CodeId != value))
				{
					this.OnCodeIdChanging(value);
					this.SendPropertyChanging();
					this._CodeId = value;
					this.SendPropertyChanged("CodeId");
					this.OnCodeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vahed", DbType="Int")]
		public System.Nullable<int> Vahed
		{
			get
			{
				return this._Vahed;
			}
			set
			{
				if ((this._Vahed != value))
				{
					this.OnVahedChanging(value);
					this.SendPropertyChanging();
					this._Vahed = value;
					this.SendPropertyChanged("Vahed");
					this.OnVahedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceKala", DbType="BigInt")]
		public System.Nullable<long> PriceKala
		{
			get
			{
				return this._PriceKala;
			}
			set
			{
				if ((this._PriceKala != value))
				{
					this.OnPriceKalaChanging(value);
					this.SendPropertyChanging();
					this._PriceKala = value;
					this.SendPropertyChanged("PriceKala");
					this.OnPriceKalaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceDastMozd", DbType="BigInt")]
		public System.Nullable<long> PriceDastMozd
		{
			get
			{
				return this._PriceDastMozd;
			}
			set
			{
				if ((this._PriceDastMozd != value))
				{
					this.OnPriceDastMozdChanging(value);
					this.SendPropertyChanging();
					this._PriceDastMozd = value;
					this.SendPropertyChanged("PriceDastMozd");
					this.OnPriceDastMozdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SumPrice", DbType="BigInt")]
		public System.Nullable<long> SumPrice
		{
			get
			{
				return this._SumPrice;
			}
			set
			{
				if ((this._SumPrice != value))
				{
					this.OnSumPriceChanging(value);
					this.SendPropertyChanging();
					this._SumPrice = value;
					this.SendPropertyChanged("SumPrice");
					this.OnSumPriceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vaheds")]
	public partial class Vahed : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public Vahed()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(200)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class FillPersonsResult
	{
		
		private int _Id;
		
		private string _FName;
		
		private string _LName;
		
		private string _FatherName;
		
		private string _CodeMelli;
		
		private string _Phone;
		
		private string _Mobile;
		
		private string _Address;
		
		private System.Nullable<int> _Hoqoqi;
		
		private string _SherkatName;
		
		public FillPersonsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FName", DbType="NVarChar(100)")]
		public string FName
		{
			get
			{
				return this._FName;
			}
			set
			{
				if ((this._FName != value))
				{
					this._FName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LName", DbType="NVarChar(100)")]
		public string LName
		{
			get
			{
				return this._LName;
			}
			set
			{
				if ((this._LName != value))
				{
					this._LName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FatherName", DbType="NVarChar(100)")]
		public string FatherName
		{
			get
			{
				return this._FatherName;
			}
			set
			{
				if ((this._FatherName != value))
				{
					this._FatherName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeMelli", DbType="NVarChar(10)")]
		public string CodeMelli
		{
			get
			{
				return this._CodeMelli;
			}
			set
			{
				if ((this._CodeMelli != value))
				{
					this._CodeMelli = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(11)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this._Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="NVarChar(11)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this._Mobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(MAX)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoqoqi", DbType="Int")]
		public System.Nullable<int> Hoqoqi
		{
			get
			{
				return this._Hoqoqi;
			}
			set
			{
				if ((this._Hoqoqi != value))
				{
					this._Hoqoqi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SherkatName", DbType="NVarChar(150)")]
		public string SherkatName
		{
			get
			{
				return this._SherkatName;
			}
			set
			{
				if ((this._SherkatName != value))
				{
					this._SherkatName = value;
				}
			}
		}
	}
	
	public partial class FillPersonsByIdResult
	{
		
		private int _Id;
		
		private string _FName;
		
		private string _LName;
		
		private string _FatherName;
		
		private string _CodeMelli;
		
		private string _Phone;
		
		private string _Mobile;
		
		private string _Address;
		
		private System.Nullable<int> _Hoqoqi;
		
		private string _SherkatName;
		
		public FillPersonsByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FName", DbType="NVarChar(100)")]
		public string FName
		{
			get
			{
				return this._FName;
			}
			set
			{
				if ((this._FName != value))
				{
					this._FName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LName", DbType="NVarChar(100)")]
		public string LName
		{
			get
			{
				return this._LName;
			}
			set
			{
				if ((this._LName != value))
				{
					this._LName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FatherName", DbType="NVarChar(100)")]
		public string FatherName
		{
			get
			{
				return this._FatherName;
			}
			set
			{
				if ((this._FatherName != value))
				{
					this._FatherName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeMelli", DbType="NVarChar(10)")]
		public string CodeMelli
		{
			get
			{
				return this._CodeMelli;
			}
			set
			{
				if ((this._CodeMelli != value))
				{
					this._CodeMelli = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(11)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this._Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="NVarChar(11)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this._Mobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(MAX)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoqoqi", DbType="Int")]
		public System.Nullable<int> Hoqoqi
		{
			get
			{
				return this._Hoqoqi;
			}
			set
			{
				if ((this._Hoqoqi != value))
				{
					this._Hoqoqi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SherkatName", DbType="NVarChar(150)")]
		public string SherkatName
		{
			get
			{
				return this._SherkatName;
			}
			set
			{
				if ((this._SherkatName != value))
				{
					this._SherkatName = value;
				}
			}
		}
	}
	
	public partial class FillVahedsResult
	{
		
		private int _Id;
		
		private string _Name;
		
		public FillVahedsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(200)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	public partial class FillPersonByLnameResult
	{
		
		private int _Id;
		
		private string _FName;
		
		private string _LName;
		
		private string _FatherName;
		
		private string _CodeMelli;
		
		private string _Phone;
		
		private string _Mobile;
		
		private string _Address;
		
		private System.Nullable<int> _Hoqoqi;
		
		private string _SherkatName;
		
		public FillPersonByLnameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FName", DbType="NVarChar(100)")]
		public string FName
		{
			get
			{
				return this._FName;
			}
			set
			{
				if ((this._FName != value))
				{
					this._FName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LName", DbType="NVarChar(100)")]
		public string LName
		{
			get
			{
				return this._LName;
			}
			set
			{
				if ((this._LName != value))
				{
					this._LName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FatherName", DbType="NVarChar(100)")]
		public string FatherName
		{
			get
			{
				return this._FatherName;
			}
			set
			{
				if ((this._FatherName != value))
				{
					this._FatherName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeMelli", DbType="NVarChar(10)")]
		public string CodeMelli
		{
			get
			{
				return this._CodeMelli;
			}
			set
			{
				if ((this._CodeMelli != value))
				{
					this._CodeMelli = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(11)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this._Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="NVarChar(11)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this._Mobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(MAX)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoqoqi", DbType="Int")]
		public System.Nullable<int> Hoqoqi
		{
			get
			{
				return this._Hoqoqi;
			}
			set
			{
				if ((this._Hoqoqi != value))
				{
					this._Hoqoqi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SherkatName", DbType="NVarChar(150)")]
		public string SherkatName
		{
			get
			{
				return this._SherkatName;
			}
			set
			{
				if ((this._SherkatName != value))
				{
					this._SherkatName = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
